/*
 * (c) Copyright 2005-2012 JAXIO, www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to use Celerio within your company? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Template pack-jsf2-primefaces:src/main/java/util/PrimeResourceHandlerWithCache.p.vm.java
 */
package ru.alex.webapp.util;

import org.primefaces.application.PrimeResourceHandler;

import javax.faces.application.Resource;
import javax.faces.application.ResourceHandler;
import java.util.HashMap;
import java.util.Map;

/**
 * This class to circumvent performance limitations observed when using composite component.
 * Indeed, createResource is invoked over and over and consumes a lot of cpu.
 */
public class PrimeResourceHandlerWithCache extends PrimeResourceHandler {

    private final Map<String, Resource> resCache = new HashMap<>();

    public PrimeResourceHandlerWithCache(ResourceHandler wrapped) {
        super(wrapped);
    }

    @Override
    public Resource createResource(String resourceName, String libraryName) {
        String key = resourceName + "__" + libraryName;
        Resource resource = resCache.get(key);

        if (resource == null) {
            resource = super.createResource(resourceName, libraryName);
            resCache.put(key, resource);
        }
        return resource;
    }
}